# Generated by Django 5.0.4 on 2024-04-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
