# Generated by Django 5.0.4 on 2024-04-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_date',
            new_name='come_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='come',
        ),
        migrations.AddField(
            model_name='attendance',
            name='back_date',
            field=models.DateField(blank=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
