# Generated by Django 5.0.4 on 2024-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_attendance_date_attendance_come_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='back_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
